--- #YAML:1.0
name:               Util-XML_YAML_Perl
version:            1.0.0
abstract:           Interconversion between PERL,YAML and XML. 
author:
    - Ravi Chandra. M <rchandram\@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:       0
    XML::Simple:      2.18
    YAML:             0.68
    YAML::AppConfig:  0.16
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
